/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JNyYY6JBxIV
 */
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export function Porfolio() {
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <header className="flex flex-col gap-1 px-4 py-4 lg:px-6 lg:py-6">
        <div className="container flex flex-col gap-2">
          <div className="space-y-1">
            <h1 className="text-2xl font-bold tracking-tighter sm:text-3xl">
              Portfolio
            </h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              UX/UI Designer and Full Stack Developer
            </p>
          </div>
          <nav className="ml-auto flex gap-4 sm:gap-6">
            <a
              className="text-sm font-medium underline-offset-4 hover:underline"
              href="#"
            >
              Projects
            </a>
            <a
              className="text-sm font-medium underline-offset-4 hover:underline"
              href="#"
            >
              About
            </a>
            <a
              className="text-sm font-medium underline-offset-4 hover:underline"
              href="#"
            >
              Contact
            </a>
          </nav>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:grid-cols-2 lg:justify-center lg:gap-10">
            <div className="space-y-2 lg:order-last">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Introduction
              </div>
              <h1 className="md:text-5xl/lg:leading-tighter text-3xl font-bold tracking-tighter">
                Hi, I'm John Doe
              </h1>
              <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                I'm a passionate UX/UI Designer and Full Stack Developer with a
                love for creating beautiful and intuitive user experiences.
                Welcome to my portfolio!
              </p>
            </div>
            <img
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center lg:aspect-video"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </section>
        <section className="w-full border-t py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Experience
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                I have worked with a variety of clients, from startups to
                Fortune 500 companies, and have helped them create amazing user
                experiences.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">User Experience Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I create intuitive and user-friendly interfaces that make it
                  easy for users to accomplish their goals.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Frontend Development</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I build beautiful and responsive websites using HTML, CSS, and
                  JavaScript.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">User Experience Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I create intuitive and user-friendly interfaces that make it
                  easy for users to accomplish their goals.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Frontend Development</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I build beautiful and responsive websites using HTML, CSS, and
                  JavaScript.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full border-t py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                My Projects
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Check out some of my recent projects.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 lg:grid-cols-3 lg:gap-12">
              <Card>
                <CardContent className="p-4">
                  <img
                    alt="Project"
                    className="aspect-video overflow-hidden rounded-lg object-cover object-center"
                    height="140"
                    src="/placeholder.svg"
                    width="250"
                  />
                </CardContent>
                <CardHeader className="p-4">
                  <CardTitle>Project One</CardTitle>
                  <CardDescription>
                    Description of the project goes here. This project was built
                    with love and hard work.
                  </CardDescription>
                </CardHeader>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <img
                    alt="Project"
                    className="aspect-video overflow-hidden rounded-lg object-cover object-center"
                    height="140"
                    src="/placeholder.svg"
                    width="250"
                  />
                </CardContent>
                <CardHeader className="p-4">
                  <CardTitle>Project Two</CardTitle>
                  <CardDescription>
                    Description of the project goes here. This project was built
                    with love and hard work.
                  </CardDescription>
                </CardHeader>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <img
                    alt="Project"
                    className="aspect-video overflow-hidden rounded-lg object-cover object-center"
                    height="140"
                    src="/placeholder.svg"
                    width="250"
                  />
                </CardContent>
                <CardHeader className="p-4">
                  <CardTitle>Project Three</CardTitle>
                  <CardDescription>
                    Description of the project goes here. This project was built
                    with love and hard work.
                  </CardDescription>
                </CardHeader>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full border-t py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                My Skills
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                I'm skilled in a variety of areas, including user experience
                design, frontend development, and more.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">User Experience Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I create intuitive and user-friendly interfaces that make it
                  easy for users to accomplish their goals.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Frontend Development</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I build beautiful and responsive websites using HTML, CSS, and
                  JavaScript.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">User Experience Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I create intuitive and user-friendly interfaces that make it
                  easy for users to accomplish their goals.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Frontend Development</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  I build beautiful and responsive websites using HTML, CSS, and
                  JavaScript.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full border-t py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Contact Me
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Have a question or want to work together? Send me a message and
                I'll get back to you as soon as possible.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="grid gap-2">
                <div className="grid gap-2">
                  <Input className="w-full" placeholder="Name" type="text" />
                  <Input className="w-full" placeholder="Email" type="email" />
                </div>
                <Textarea
                  className="min-h-[100px] resize-none"
                  placeholder="Message"
                />
                <Button type="submit">Send Message</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
